# I am a comment, and I want to say that the variable CC will be
# the compiler to use.
CC=gcc
# Hey!, I am comment number 2. I want to say that CFLAGS will be the
# options I'll pass to the compiler.
CFLAGS=-c -Wall -g
SUBS = testHelpers stack queue linked_list tree linked_list_tests \
	stack_queue_tests
OFILES := $(foreach file, $(SUBS), $(file).o)

all: Algo

Algo: $(SUBS)
	$(CC) -Wall -g test/setsInC.c $(OFILES) -o algo

tree: sets/tree.c
	$(CC) $(CFLAGS) sets/tree.c

testHelpers: test/test.c
	$(CC) $(CFLAGS) test/test.c -o testHelpers.o

linked_list_tests: test/linked_list_tests.c
	$(CC) $(CFLAGS) test/linked_list_tests.c

stack_queue_tests: test/stack_queue_tests.c
	$(CC) $(CFLAGS) test/stack_queue_tests.c

linked_list: sets/linked_list.c
	$(CC) $(CFLAGS) sets/linked_list.c

queue: sets/queue.c
	$(CC) $(CFLAGS) sets/queue.c

stack: sets/stack.c
	$(CC) $(CFLAGS) sets/stack.c

clean:
	rm *.o algo
